name: Create Repo

on:
  push:
    branches:
      - abhigyantest
# env:
#   # Replace with the actual repository name
#   REPOSITORY_NAME: my-artifact-repository

#   # Replace with the desired location (e.g., us-central1)
#   LOCATION: us-central1
  # workflow_dispatch:
  #   inputs:
  #     repository_name:
  #       description: 'Name of the repository'
  #       required: true
  #     location:
  #       description: 'Location for the repository'
  #       required: true

jobs:
  authenticate:
    runs-on: ubuntu-latest
    env:
     path: "${{ github.workspace }}/CICD"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Print workflow name
        run: |
          echo "${{ github.workspace }}"
          cd path
          pwd
        
      - name: "Say Hello Mona it's Monday"
        run:  echo "${{ vars.LOCATION }}".
        
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Check if the repository exists
        id: check_repo
        run: |
          if gcloud artifacts repositories describe ${{ vars.REPOSITORY_NAME }} --location=${{ vars.LOCATION }} >/dev/null 2>&1; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
        continue-on-error: true
      - name: Create the repository if it doesn't exist
        if: steps.check_repo.outputs.exists == 'false'
        run: |
          gcloud artifacts repositories create ${{ vars.REPOSITORY_NAME }} --location=${{ vars.LOCATION }} --repository-format=docker
