name: Create Repo

on:
  push:
    branches:
      - abhigyantest

variables:
  # Replace with the actual repository name
  REPOSITORY_NAME: my-artifact-repository

  # Replace with the desired location (e.g., us-central1)
  LOCATION: us-central1

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          # Consider using workload identity or uploaded service account key

      - name: Check if the repository exists
        id: check_repo
        run: |
          if gcloud artifacts repositories describe ${{ variables.REPOSITORY_NAME }} --location=${{ variables.LOCATION }} >/dev/null 2>&1; then
            echo "Repository already exists."
          else
            echo "Repository not found. Creating..."
            gcloud artifacts repositories create ${{ variables.REPOSITORY_NAME }} --location=${{ variables.LOCATION }} --repository-format=docker
          fi
        continue-on-error: false  # Fail workflow if check fails
