name: Create Repo

on:
  push:
    branches:
      - abhigyantest
  # workflow_dispatch:
  #   inputs:
  #     repository_name:
  #       description: 'Name of the repository'
  #       required: true
  #     location:
  #       description: 'Location for the repository'
  #       required: true

jobs:
  authenticate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Check if the repository exists
        id: check_repo
        run: |
          if gcloud artifacts repositories describe ${{ variables.REPOSITORY_NAME }} --location=${{ variables.LOCATION }} >/dev/null 2>&1; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi
        continue-on-error: true
        env:
          location: ${{ variables.LOCATION }}
      - name: Create the repository if it doesn't exist
        if: steps.check_repo.outputs.exists == 'false'
        run: |
          gcloud artifacts repositories create ${{ variables.REPOSITORY_NAME }} --location=${{ variables.LOCATION }} --repository-format=docker
        env:
          location: ${{ variables.LOCATION }}
